version: "3.7"

services:
  db:
    image: postgres:9.6.17-alpine
    container_name: db
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: stormtroopers
      POSTGRES_USER: db_user
      # DO NOT PUT SECRETS IN SOURCE CONTROL
      POSTGRES_PASSWORD: super_secret
    volumes:
      - ./db/dev:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  app:
    build: server
    container_name: app
    ports:
    - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/stormtroopers"
      SPRING_DATASOURCE_USERNAME: db_user
      # DO NOT PUT SECRETS IN SOURCE CONTROL
      SPRING_DATASOURCE_PASSWORD: super_secret
    depends_on:
      - db

  frontend:
    build: frontend
    ports:
      - 8081:8081
    volumes:
      - ./frontend:/app
    environment:
      PROXY_TARGET_URL: "http://app:8080"
    depends_on:
      - app