
spring:
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/stormtroopers"
    username: db_user
    password: super_secret